// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK-SHiFQMayeDPJ3X5XU1bXJ5dRio9DjU',
    appId: '1:1065717162929:web:2bf5c53bfc0b1e177d5390',
    messagingSenderId: '1065717162929',
    projectId: 'notes--plus',
    authDomain: 'notes--plus.firebaseapp.com',
    storageBucket: 'notes--plus.appspot.com',
    measurementId: 'G-KXD0G2MBRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkccdY0Ujt59riyZRk3BXHZiudizjbrMw',
    appId: '1:1065717162929:android:ee8b300e127bb1707d5390',
    messagingSenderId: '1065717162929',
    projectId: 'notes--plus',
    storageBucket: 'notes--plus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIm9XEI_6gbb_3iIFo_59fyYeBw3TuJ3I',
    appId: '1:1065717162929:ios:707bd44fea327adb7d5390',
    messagingSenderId: '1065717162929',
    projectId: 'notes--plus',
    storageBucket: 'notes--plus.appspot.com',
    iosClientId: '1065717162929-ii0mqukeibbn3a6h9us6dh6knbfsb7mp.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIm9XEI_6gbb_3iIFo_59fyYeBw3TuJ3I',
    appId: '1:1065717162929:ios:4a8140af6bc2628c7d5390',
    messagingSenderId: '1065717162929',
    projectId: 'notes--plus',
    storageBucket: 'notes--plus.appspot.com',
    iosClientId: '1065717162929-q1hh69crmsdhejhobt664sesdjfkac85.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesPlus.RunnerTests',
  );
}
